#!/usr/bin/env python3
"""
Pre-processes games.san into a compact C++ header for embedding the opening book.
Truncates each game to the first 30 half-moves (15 per side) and outputs a string array.
"""

import sys
from lib.path import PROJECT_ROOT

OPENING_CUTOFF_PLY = 30
INPUT_PATH = PROJECT_ROOT / 'positions' / 'games.san'
OUTPUT_PATH = PROJECT_ROOT / 'src' / 'data' / 'book.hpp'


def truncate_game(line: str) -> str:
    """Trim a game line to the first OPENING_CUTOFF_PLY half-moves."""
    moves = line.strip().split()
    return ' '.join(moves[:OPENING_CUTOFF_PLY])


def main():
    """Read games.san, truncate and deduplicate openings, and write src/data/book.hpp."""
    if not INPUT_PATH.exists():
        print(f'Error: {INPUT_PATH} not found', file=sys.stderr)
        sys.exit(1)

    games = []
    with open(INPUT_PATH) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            truncated = truncate_game(line)
            if truncated:
                games.append(truncated)

    # Deduplicate identical openings
    games = sorted(set(games))

    with open(OUTPUT_PATH, 'w') as out:
        out.write('// Auto-generated by scripts/generators/book.py — do not edit manually\n\n')
        out.write('#pragma once\n\n')
        out.write(f'inline const size_t BOOK_SIZE = {len(games)};\n\n')
        out.write(f'inline const char* const BOOK_DATA[] = {{\n')
        for game in games:
            escaped = game.replace('\\', '\\\\').replace('"', '\\"')
            out.write(f'    "{escaped}",\n')
        out.write('};\n')

    print(f'Generated {OUTPUT_PATH}')
    print(f'  {len(games)} unique openings (from {INPUT_PATH})')

if __name__ == '__main__':
    main()
