#!/usr/bin/env python3
"""
Generates src/data/params.hpp from tuned parameter pickle.

Usage:
    python -m generators.params
"""

from lib.path import PROJECT_ROOT, script_path
from lib.versioned import resolve, load_pickle, save_pickle

DATA_DIR = PROJECT_ROOT / 'scripts' / 'tune' / 'data'
PREFIX = 'params'
OUTPUT = PROJECT_ROOT / 'src' / 'data' / 'params.hpp'

PARAMS = [
    # Search
    ('AspirationWindow', 'ASPIRATION_WINDOW', 25),
    ('NullMoveBaseReduction', 'NULL_MOVE_BASE_REDUCTION', 2),
    ('NullMoveDeeperThreshold', 'NULL_MOVE_DEEPER_THRESHOLD', 6),
    ('NullMoveMinDepth', 'NULL_MOVE_MIN_DEPTH', 3),
    ('ReverseFutilityMarginPerDepth', 'REVERSE_FUTILITY_MARGIN_PER_DEPTH', 80),
    ('ReverseFutilityMarginBase', 'REVERSE_FUTILITY_MARGIN_BASE', 0),
    ('ReverseFutilityMaxDepth', 'REVERSE_FUTILITY_MAX_DEPTH', 7),
    ('FutilityMarginPerDepth', 'FUTILITY_MARGIN_PER_DEPTH', 90),
    ('FutilityMarginBase', 'FUTILITY_MARGIN_BASE', 40),
    ('FutilityMaxDepth', 'FUTILITY_MAX_DEPTH', 4),
    ('LMPBase', 'LMP_BASE', 3),
    ('LMPMaxDepth', 'LMP_MAX_DEPTH', 4),
    ('RazoringMargin', 'RAZORING_MARGIN', 200),
    ('RazoringMaxDepth', 'RAZORING_MAX_DEPTH', 1),
    ('SEEPruningMaxDepth', 'SEE_PRUNING_MAX_DEPTH', 4),
    ('ReducedSearchMinDepth', 'REDUCED_SEARCH_MIN_DEPTH', 7),
    ('ReducedSearchDepthDivisor', 'REDUCED_SEARCH_DEPTH_DIVISOR', 2),
    ('ReducedSearchMarginMultiplier', 'REDUCED_SEARCH_MARGIN_MULTIPLIER', 2),
    ('ReducedSearchTTDepthMargin', 'REDUCED_SEARCH_TT_DEPTH_MARGIN', 3),
    ('SEECutoff', 'SEE_CUTOFF', -200),
    ('LMRTuningConstant', 'LMR_TUNING_CONSTANT', 2.0),
    ('MinimumIIDDepth', 'MINIMUM_IID_DEPTH', 4),
    ('IIDDepthDivisor', 'IID_DEPTH_DIVISOR', 2),
    ('LMRPVReduction', 'LMR_PV_REDUCTION', 1),
    ('NullMoveDeepReduction', 'NULL_MOVE_DEEP_REDUCTION', 5),
    ('HistoryMalusDivisor', 'HISTORY_MALUS_DIVISOR', 2),
]


def _load_params():
    """Load latest tuned params, injecting defaults for any new entries."""
    path = resolve(DATA_DIR, PREFIX, '.pkl')
    if path is None:
        params = {name: default for name, _, default in PARAMS}
        saved = save_pickle(DATA_DIR, PREFIX, params)
        print(f'No tuned params found, initialized defaults at {saved}')
        return params

    params = load_pickle(path)
    # Strip SPSA metadata if present
    params.pop('_spsa_state', None)
    for name, _, default in PARAMS:
        if name not in params:
            params[name] = default
    return params


def main():
    """Generate the C++ params header."""
    params = _load_params()

    with open(OUTPUT, 'w') as f:
        f.write(f'// Auto-generated by {script_path(__file__)} — do not edit manually\n\n')
        f.write('#pragma once\n\n')

        for uci_name, const_name, default in PARAMS:
            val = params.get(uci_name, default)
            if isinstance(default, int):
                f.write(f'constexpr int DEFAULT_{const_name} = {round(val)};\n')
            else:
                f.write(f'constexpr double DEFAULT_{const_name} = {val};\n')

    print(f'Wrote params to {OUTPUT}')


if __name__ == '__main__':
    main()
