#!/usr/bin/env python3
"""
Generates src/data/search_params.hpp from tuned search parameter values.

Reads a pickle dict of UCI param name -> value, and writes a header with
DEFAULT_* constants that params.hpp uses as struct field defaults.
"""

import sys

from lib.path import PROJECT_ROOT, script_path
from lib.versioned import resolve, load_pickle, save_pickle

PARAMS_DIR = PROJECT_ROOT / 'scripts' / 'tune' / 'data' / 'search_params'
PARAMS_PREFIX = 'search_params'
OUTPUT_PATH = PROJECT_ROOT / 'src' / 'data' / 'search_params.hpp'

# UCI name -> (C++ constant suffix, default value)
# Defaults are used to bootstrap the pickle if none exists.
PARAM_MAP = [
    ("AspirationWindow", "ASPIRATION_WINDOW", 25),
    ("ScoreDropThreshold", "SCORE_DROP_THRESHOLD", 50),
    ("NullMoveBaseReduction", "NULL_MOVE_BASE_REDUCTION", 2),
    ("NullMoveDeeperThreshold", "NULL_MOVE_DEEPER_THRESHOLD", 6),
    ("NullMoveMinDepth", "NULL_MOVE_MIN_DEPTH", 3),
    ("FutilityMarginPerDepth", "FUTILITY_MARGIN_PER_DEPTH", 90),
    ("FutilityMarginBase", "FUTILITY_MARGIN_BASE", 40),
    ("FutilityMaxDepth", "FUTILITY_MAX_DEPTH", 4),
    ("SEECutoff", "SEE_CUTOFF", -200),
    ("LMRTuningConstant", "LMR_TUNING_CONSTANT", 2.0),
    ("MinimumIIDDepth", "MINIMUM_IID_DEPTH", 4),
    ("IIDDepthDivisor", "IID_DEPTH_DIVISOR", 2),
    ("LMRPVReduction", "LMR_PV_REDUCTION", 1),
    ("BestMoveMinStability", "BEST_MOVE_MIN_STABILITY", 0),
    ("NullMoveDeepReduction", "NULL_MOVE_DEEP_REDUCTION", 5),
    ("HistoryMalusDivisor", "HISTORY_MALUS_DIVISOR", 2),
]


def _load_params():
    """Load latest tuned params or initialize with defaults."""
    path = resolve(PARAMS_DIR, PARAMS_PREFIX, '.pkl')
    if path is not None:
        return load_pickle(path)

    params = {name: default for name, _, default in PARAM_MAP}
    saved = save_pickle(PARAMS_DIR, PARAMS_PREFIX, params)
    print(f'No tuned params found, initialized defaults at {saved}')
    return params


def main():
    params = _load_params()

    with open(OUTPUT_PATH, 'w') as f:
        f.write(f'// Auto-generated by {script_path(__file__)} — do not edit manually\n\n')
        f.write('#pragma once\n\n')

        for uci_name, const_name, default in PARAM_MAP:
            val = params.get(uci_name, default)
            if isinstance(default, int):
                f.write(f'constexpr int DEFAULT_{const_name} = {round(val)};\n')
            else:
                f.write(f'constexpr double DEFAULT_{const_name} = {val};\n')

    print(f'Wrote search params to {OUTPUT_PATH}')


if __name__ == '__main__':
    main()