#!/usr/bin/env python3
"""
Generates src/data/tm_params.hpp from tuned time management parameter values.

Reads a pickle dict of UCI param name -> value, and writes a header with
DEFAULT_* constants that params.hpp uses as struct field defaults.
"""

from lib.path import PROJECT_ROOT, script_path
from lib.versioned import resolve, load_pickle, save_pickle

PARAMS_DIR = PROJECT_ROOT / 'scripts' / 'tune' / 'data' / 'tm_params'
PARAMS_PREFIX = 'tm_params'
OUTPUT_PATH = PROJECT_ROOT / 'src' / 'data' / 'tm_params.hpp'

# UCI name -> (C++ constant suffix, default value)
# Defaults are the pre-tuning baseline values.
PARAM_MAP = [
    ("MovesLeftBase", "MOVES_LEFT_BASE", 10),
    ("MovesLeftPhaseScale", "MOVES_LEFT_PHASE_SCALE", 30),
    ("MinMovesNoIncrement", "MIN_MOVES_NO_INCREMENT", 45),
    ("IncrementFraction", "INCREMENT_FRACTION", 0.5),
    ("SoftFactorNoIncrement", "SOFT_FACTOR_NO_INCREMENT", 0.5),
    ("SoftFactorIncrement", "SOFT_FACTOR_INCREMENT", 0.6),
    ("HardFactor", "HARD_FACTOR", 2.625),
    ("HardCapDivisor", "HARD_CAP_DIVISOR", 3),
    ("EmergencyTrigger", "EMERGENCY_TRIGGER", 4),
    ("EmergencySoftDivisor", "EMERGENCY_SOFT_DIVISOR", 15),
    ("EmergencyHardDivisor", "EMERGENCY_HARD_DIVISOR", 8),
]


def _load_params():
    """Load latest tuned params or initialize with defaults."""
    path = resolve(PARAMS_DIR, PARAMS_PREFIX, '.pkl')
    if path is not None:
        return load_pickle(path)

    params = {name: default for name, _, default in PARAM_MAP}
    saved = save_pickle(PARAMS_DIR, PARAMS_PREFIX, params)
    print(f'No tuned params found, initialized defaults at {saved}')
    return params


def main():
    params = _load_params()

    with open(OUTPUT_PATH, 'w') as f:
        f.write(f'// Auto-generated by {script_path(__file__)} — do not edit manually\n\n')
        f.write('#pragma once\n\n')

        for uci_name, const_name, default in PARAM_MAP:
            val = params.get(uci_name, default)
            if isinstance(default, int):
                f.write(f'constexpr int DEFAULT_{const_name} = {round(val)};\n')
            else:
                f.write(f'constexpr double DEFAULT_{const_name} = {val};\n')

    print(f'Wrote TM params to {OUTPUT_PATH}')


if __name__ == '__main__':
    main()
