#!/usr/bin/env python3
"""
Quantizes trained NNUE weights into fixed-point integers for the C++ engine
and writes them to a generated header file.

Quantization scheme:

Q1 (127) — Feature transformer scale. Chosen to fill the int8 output range
after ClippedReLU clamps the accumulator to [0, 127]. Weights are int16
because the scaled values exceed int8's [-128, 127] range.

Q2 (64) — Hidden layer weight scale. Power of 2 so dequantization is a
bit shift (>> 6) instead of a division. Weights fit comfortably in int8.

Layer 1 has no matmul — it sums embedding rows into an int16 accumulator,
so weights and biases share the same scale (Q1) and are both int16.

Layers 2/3 have a real matmul where inputs (scaled by Q1) multiply weights
(scaled by Q2), so the accumulator is scaled by Q1*Q2. Biases are int32 at
that combined scale so they can be added directly to the int32 matmul
accumulator. After adding the bias, >> 6 brings it back to Q1 scale.

The output layer uses a custom weight scale qeval = Q2 / (Q1 * eval_scale)
instead of Q2, where eval_scale is the sigmoid constant from training. This
bakes the centipawn conversion into the weights so that >> 6 on the int32
result yields centipawns directly, with no float math in the engine.
"""

import torch
import numpy as np
from nnue.weights import resolve_weights
from lib.path import PROJECT_ROOT

OUTPUT_PATH = PROJECT_ROOT / 'src' / 'data' / 'weights.hpp'

Q1 = 127
Q2 = 64


def quantize(tensor, scale, dtype):
    """Scale a tensor, round to integers, and check for overflow before casting to dtype."""
    arr = (tensor * scale).round().numpy()
    info = np.iinfo(dtype)
    if arr.min() < info.min or arr.max() > info.max:
        raise OverflowError(f'Quantized values [{arr.min():.0f}, {arr.max():.0f}] exceed {dtype.__name__} range [{info.min}, {info.max}]')
    return arr.astype(dtype)


def check_accumulator_overflow(weights, biases):
    """Verify int16 accumulators can't overflow. Upper bound assumes all 30 non-king
    pieces activate the largest weight on the same accumulator element."""
    max_accumulator = int(np.max(np.abs(biases))) + 30 * int(np.max(np.abs(weights)))
    if max_accumulator > np.iinfo(np.int16).max:
        raise OverflowError(f'Worst-case accumulator value {max_accumulator} exceeds int16 range')


def load_and_quantize_parameters():
    """Loads and quantizes learned weights and biases. Returns the learned parameters along with
    the fitted evaluation scaling factor in a dict"""
    params = {}

    checkpoint = torch.load(resolve_weights(), weights_only=False, map_location='cpu')
    parameters = checkpoint['model']
    eval_scaling_factor = checkpoint['eval_scaling_factor']
    qeval = Q2 / (Q1 * eval_scaling_factor)
   
    params['qlayer1_weight'] = quantize(parameters['layer1.weight'], Q1, np.int16)
    params['qlayer1_bias'] = quantize(parameters['layer1_bias'], Q1, np.int16)
    check_accumulator_overflow(params['qlayer1_weight'], params['qlayer1_bias'])

    params['qlayer2_weight'] = quantize(parameters['layer2.weight'], Q2, np.int8)
    params['qlayer2_bias'] = quantize(parameters['layer2.bias'], Q1 * Q2, np.int32)

    params['qlayer3_weight'] = quantize(parameters['layer3.weight'], Q2, np.int8)
    params['qlayer3_bias'] = quantize(parameters['layer3.bias'], Q1 * Q2, np.int32)

    params['qoutput_weight'] = quantize(parameters['output.weight'].flatten(), qeval, np.int16)
    params['qoutput_bias'] = quantize(parameters['output.bias'], Q1 * qeval, np.int32).item()

    return params


def write_array(file, type, name, array):
    """Write a C++ array declaration with flat-initializer syntax."""
    dim = ''.join(f'[{d}]' for d in array.shape)
    flat = ', '.join(str(x) for x in array.flatten())
    file.write(f'alignas(64) inline const {type} {name}{dim} = {{ {flat} }};\n')


def main():
    """Quantize the latest trained weights and write them to src/data/weights.hpp."""
    params = load_and_quantize_parameters()

    with open(OUTPUT_PATH, 'w') as file:
        file.write('// Auto-generated by scripts/generators/weights.py — do not edit manually\n\n')
        file.write('#pragma once\n\n')

        file.write('#include <cstddef>\n')
        file.write('#include <cstdint>\n\n')

        file.write(f'constexpr int32_t Q1 = {Q1};\n')
        file.write(f'constexpr int32_t Q2 = {Q2};\n\n')

        file.write(f'constexpr size_t L1_SIZE = {params["qlayer1_weight"].shape[1]};\n')
        file.write(f'constexpr size_t L2_SIZE = {params["qlayer2_weight"].shape[0]};\n')
        file.write(f'constexpr size_t L3_SIZE = {params["qlayer3_weight"].shape[0]};\n\n')

        write_array(file, 'int16_t', 'L1_WEIGHT', params['qlayer1_weight'])
        write_array(file, 'int16_t', 'L1_BIAS', params['qlayer1_bias'])
        file.write('\n')

        write_array(file, 'int8_t', 'L2_WEIGHT', params['qlayer2_weight'])
        write_array(file, 'int32_t', 'L2_BIAS', params['qlayer2_bias'])
        file.write('\n')

        write_array(file, 'int8_t', 'L3_WEIGHT', params['qlayer3_weight'])
        write_array(file, 'int32_t', 'L3_BIAS', params['qlayer3_bias'])
        file.write('\n')

        write_array(file, 'int16_t', 'OUTPUT_WEIGHT', params['qoutput_weight'])
        file.write(f'inline const int32_t OUTPUT_BIAS = {params["qoutput_bias"]};\n')

if __name__ == '__main__':
    main()