#!/usr/bin/env python3
"""
NNUE trainer for the Enigma chess engine.

Trains a HalfKP neural network on self-play data generated by datagen.py.
"""

import argparse
import time
import math
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from scipy.special import expit
from scipy.optimize import minimize_scalar
from dataclasses import dataclass
from nnue.paths import (
    TRAINING_DATA_DIR, TRAINING_DATA_GLOB,
    VALIDATION_DATA_DIR, VALIDATION_DATA_GLOB,
    WEIGHTS_DIR,
)
from lib.versioned import resolve, next_path

# --- Constants ---

# HalfKP feature space = 64 king squares * 2 sides * 5 pieces * 64 squares = 40960
FEATURE_VECTOR_SIZE = 40960
INPUT_LAYER_SIZE = FEATURE_VECTOR_SIZE
HIDDEN_LAYER_1_SIZE = 256
HIDDEN_LAYER_2_SIZE = 32
HIDDEN_LAYER_3_SIZE = 32
OUTPUT_LAYER_SIZE = 1

# Enigma's side encoding (see src/types.hpp)
WHITE = 0
BLACK = 1

# Enigma's piece encoding (see src/types.hpp)
PAWN = 0
KNIGHT = 1
BISHOP = 2
ROOK = 3
QUEEN = 4
KING = 5
NO_PIECE = 6

# Training constants
TRAINNG_BATCH_SIZE = 16384
INITIAL_LEARNING_RATE = 0.0001
LEARNING_RATE_STEP_SIZE = 10
LEARNING_RATE_GAMMA = 0.5
EVALUATION_WEIGHT = 0.5
MAX_POSITIONS = None
NUM_EPOCHS = 100
WEIGHT_DECAY = 0.0001
GRADIENT_CLIP_MAX_NORM = 1.0
EARLY_STOPPING_PATIENCE = 10
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
LOSS_FUNCTION = nn.BCELoss()


# --- Model ---


class NNUE(nn.Module):
    """HalfKP NNUE model.

    Architecture: EmbeddingBag(40960, 256) -> Linear(512, 32) -> Linear(32, 32) -> Linear(32, 1)

    The first layer is the key design choice. HalfKP encodes each non-king piece
    relative to its own king's square, producing a 40,960-dimensional feature vector
    that is extremely sparse (~30 active features out of 40,960). Using EmbeddingBag
    instead of Linear avoids multiplying by the ~40,930 zeros; it just looks up and
    sums the rows for the active features. Mathematically identical to a dense matmul,
    but drastically faster.

    Both sides maintain their own accumulator (white perspective and black perspective)
    through the shared first layer. In the engine, these accumulators can be updated
    incrementally as pieces move rather than recomputed from scratch. The two
    accumulator outputs are concatenated as [ours, theirs] based on the side to move,
    so the network always sees its own perspective first. This feeds into standard
    dense layers that produce a win probability via sigmoid.
    """

    def __init__(self):
        super().__init__()

        self.layer1 = nn.EmbeddingBag(INPUT_LAYER_SIZE, HIDDEN_LAYER_1_SIZE, mode='sum')
        nn.init.normal_(self.layer1.weight, mean=0, std=1/math.sqrt(30))
        # EmbeddingBag has no built-in bias, so we add one as a learnable parameter
        self.layer1_bias = nn.Parameter(torch.zeros(HIDDEN_LAYER_1_SIZE))

        # Input is 2x layer 1 output size since we concatenate both perspective accumulators
        self.layer2 = nn.Linear(HIDDEN_LAYER_1_SIZE * 2, HIDDEN_LAYER_2_SIZE)
        self.layer3 = nn.Linear(HIDDEN_LAYER_2_SIZE, HIDDEN_LAYER_3_SIZE)
        self.output = nn.Linear(HIDDEN_LAYER_3_SIZE, OUTPUT_LAYER_SIZE)

    @staticmethod
    def clipped_relu(x):
        return torch.clamp(x, 0.0, 1.0)

    def forward(self, white_indices, white_offsets, black_indices, black_offsets, side_to_move):
        l1_w = self.clipped_relu(self.layer1(white_indices, white_offsets) + self.layer1_bias)
        l1_b = self.clipped_relu(self.layer1(black_indices, black_offsets) + self.layer1_bias)
        # Concatenate as [ours, theirs] based on side to move
        stm = side_to_move.unsqueeze(1)
        l1_first = torch.where(stm == WHITE, l1_w, l1_b)
        l1_second = torch.where(stm == WHITE, l1_b, l1_w)
        l1 = torch.concat([l1_first, l1_second], dim=1)
        l2 = self.clipped_relu(self.layer2(l1))
        l3 = self.clipped_relu(self.layer3(l2))
        return torch.sigmoid(self.output(l3)).squeeze(1)


@dataclass
class Batch:
    """A collated batch of positions ready for the model."""
    white_indices: torch.Tensor
    white_offsets: torch.Tensor
    black_indices: torch.Tensor
    black_offsets: torch.Tensor
    side_to_move: torch.Tensor
    score: torch.Tensor
    outcome: torch.Tensor


class BatchSampler:
    """Generates shuffled batches of position indices for each epoch.

    Position indices are integers [0, num_positions) that map directly into
    PositionDataset's arrays. Each epoch produces a fresh shuffle so the
    model sees different batch compositions each time.

    Uses NumPy for shuffling (faster than torch.randperm().tolist() for large datasets).
    """

    def __init__(self, num_positions, batch_size):
        self.num_positions = num_positions
        self.batch_size = batch_size

    def __iter__(self):
        """Shuffle all position indices and yield them in batch-sized chunks.
        Called once per epoch by DataLoader, ensuring different batch compositions each time."""
        indices = np.random.permutation(self.num_positions)
        for i in range(0, self.num_positions, self.batch_size):
            yield indices[i:i + self.batch_size].tolist()

    def __len__(self):
        """Returns the number of batches in the dataset (ceiling division)."""
        return (self.num_positions + self.batch_size - 1) // self.batch_size


class PositionDataset:
    """All position data stored as flat arrays on the compute device, indexed by position number.

    Each position has a score, outcome, side to move, and a variable-length list of
    HalfKP feature indices stored in the flat all_white/all_black arrays. feature_offsets[i]
    marks where position i's features start, so features for position i are
    all_white[feature_offsets[i]:feature_offsets[i+1]]."""

    def __init__(self, side_to_moves, scores, outcomes, all_white, all_black, feature_offsets):
        self.side_to_moves = torch.from_numpy(side_to_moves).to(DEVICE)
        self.scores = torch.from_numpy(scores.astype(np.float32)).to(DEVICE)
        self.outcomes = torch.from_numpy(outcomes).to(DEVICE)
        self.all_white = torch.from_numpy(all_white.astype(np.int32)).to(DEVICE)
        self.all_black = torch.from_numpy(all_black.astype(np.int32)).to(DEVICE)
        self.feature_offsets = torch.from_numpy(feature_offsets).to(DEVICE)

        total_bytes = sum(t.nbytes for t in [self.scores, self.outcomes, self.all_white, self.all_black, self.feature_offsets])
        mem_type = 'VRAM' if DEVICE.type == 'cuda' else 'RAM'
        print(f'Uploaded {total_bytes / 1e9:.1f} GB to {mem_type}')

    def __len__(self):
        """Required by DataLoader interface; batching is handled by BatchSampler."""
        return len(self.scores)

    def __getitem__(self, index):
        """Required by DataLoader interface; actual data loading is done in collate()."""
        return index

    def collate(self, indices):
        """Take a batch of position indices, gather their variable-length feature slices,
        and assemble them into the flat (indices, offsets) format that EmbeddingBag expects."""
        indices = torch.tensor(indices, dtype=torch.long, device=DEVICE)
        starts = self.feature_offsets[indices]
        ends = self.feature_offsets[indices + 1]
        counts = ends - starts
        total = int(counts.sum())

        # Vectorized gather of variable-length slices from the flat arrays
        cumcounts = torch.zeros(len(counts), dtype=torch.long, device=DEVICE)
        cumcounts[1:] = counts[:-1].cumsum(0)
        flat_index = starts.repeat_interleave(counts) - cumcounts.repeat_interleave(counts) + torch.arange(total, device=DEVICE)

        return Batch(
            white_indices=self.all_white[flat_index].long(),
            white_offsets=cumcounts,
            black_indices=self.all_black[flat_index].long(),
            black_offsets=cumcounts,
            side_to_move=self.side_to_moves[indices],
            score=self.scores[indices],
            outcome=self.outcomes[indices],
        )


# --- Feature Computation ---


def _decode_board(pieces):
    """Unpack nibble-encoded board bytes into side and piece arrays."""
    # python-chess: WHITE=1, BLACK=0; enigma: WHITE=0, BLACK=1
    PC_TO_ENIGMA_SIDE = np.array([BLACK, WHITE], dtype=np.int32)
    # python-chess piece types are 1-indexed (PAWN=1..KING=6); enigma is 0-indexed
    PC_TO_ENIGMA_PIECE = np.array([NO_PIECE, PAWN, KNIGHT, BISHOP, ROOK, QUEEN, KING], dtype=np.int32)

    chunk_size = len(pieces)
    low_nibbles = pieces & 0x0F # even squares
    high_nibbles = pieces >> 4 # odd squares
    nibbles = np.empty((chunk_size, 64), dtype=np.uint8)
    nibbles[:, 0::2] = low_nibbles
    nibbles[:, 1::2] = high_nibbles

    pc_side = nibbles >> 3
    pc_piece = nibbles & 0x07
    side = PC_TO_ENIGMA_SIDE[pc_side]
    piece = PC_TO_ENIGMA_PIECE[pc_piece]
    return side, piece


def _find_king_squares(side, piece):
    """Return the square index of each side's king for every position."""
    is_white_king = (side == WHITE) & (piece == KING)
    is_black_king = (side == BLACK) & (piece == KING)
    white_king_sq = np.argmax(is_white_king, axis=1)
    black_king_sq = np.argmax(is_black_king, axis=1)
    return white_king_sq, black_king_sq


def _compute_halfkp_indices(side, piece, white_king_sq, black_king_sq):
    """Compute HalfKP feature indices for both perspectives."""
    chunk_size = len(side)

    # Mask for non-empty, non-king squares
    mask = (piece != NO_PIECE) & (piece != KING)

    # Flatten to parallel arrays of (chunk_index, square) for active pieces
    chunk_index, sq_index = np.where(mask)
    masked_side = side[chunk_index, sq_index]
    masked_piece = piece[chunk_index, sq_index]
    masked_sq = sq_index.astype(np.int32)

    # White perspective indices
    white_feat_index = (
        white_king_sq[chunk_index] * 2 * 5 * 64
        + masked_side * 5 * 64
        + masked_piece * 64
        + masked_sq
    )
    # Black perspective mirrors squares vertically (^ 56) and flips side
    black_feat_index = (
        (black_king_sq[chunk_index] ^ 56) * 2 * 5 * 64
        + (masked_side ^ 1) * 5 * 64
        + masked_piece * 64
        + (masked_sq ^ 56)
    )
    
    offsets = np.searchsorted(chunk_index, np.arange(chunk_size))

    return (
        white_feat_index.astype(np.int64),
        black_feat_index.astype(np.int64),
        offsets.astype(np.int64),
    )


def _compute_features(pieces):
    """Convert raw board bytes into HalfKP feature indices."""
    side, piece = _decode_board(pieces)
    white_king_sq, black_king_sq = _find_king_squares(side, piece)
    return _compute_halfkp_indices(side, piece, white_king_sq, black_king_sq)


# --- Data Loading ---


def _load_raw_positions(data_dir, data_glob, max_positions=None):
    """Read .bin data files and extract pieces, side to move, scores, and outcomes."""
    NUM_BYTES_POSITION = 36
    OUTCOME_MAP = np.array([0.5, 1.0, 0.0], dtype=np.float32)

    chunks = []
    for file in sorted(data_dir.glob(data_glob)):
        chunks.append(np.fromfile(file, dtype=np.uint8))

    if not chunks:
        raise FileNotFoundError(
            f"No data files found matching '{data_glob}' in {data_dir}/\n"
            f'Generate data first:  uv run -m nnue.datagen'
            + (' --validation' if 'validation' in data_glob else '')
        )

    raw = np.concatenate(chunks).reshape(-1, NUM_BYTES_POSITION)
    if max_positions and max_positions < len(raw):
        indices = np.random.choice(len(raw), max_positions, replace=False)
        raw = raw[indices]
    print(f'Loaded {len(raw):,} positions')

    pieces = raw[:, :32]
    side_to_moves = raw[:, 32]
    scores = raw[:, 33:35].view(np.int16).squeeze()
    outcomes = OUTCOME_MAP[raw[:, 35]]
    return pieces, side_to_moves, scores, outcomes


def _precompute_features(pieces):
    """Compute HalfKP features for all positions in chunks."""
    PRECOMPUTE_CHUNK = 65536
    n = len(pieces)

    t = time.perf_counter()
    white_chunks = []
    black_chunks = []
    counts = []
    for i in range(0, n, PRECOMPUTE_CHUNK):
        chunk = pieces[i:i + PRECOMPUTE_CHUNK]
        w, b, offsets = _compute_features(chunk)
        chunk_counts = np.diff(np.append(offsets, len(w)))
        white_chunks.append(w)
        black_chunks.append(b)
        counts.append(chunk_counts)

    all_white = np.concatenate(white_chunks).astype(np.uint16)
    all_black = np.concatenate(black_chunks).astype(np.uint16)
    all_counts = np.concatenate(counts)
    feature_offsets = np.zeros(n + 1, dtype=np.int64)
    np.cumsum(all_counts, out=feature_offsets[1:])
    print(f'Precomputed {len(all_white):,} feature entries in {time.perf_counter() - t:.1f}s')
    return all_white, all_black, all_counts, feature_offsets


def _load_positions(data_dir, data_glob, max_positions=None):
    """Load positions from .bin files, precompute features, and shuffle."""
    pieces, side_to_moves, scores, outcomes = _load_raw_positions(data_dir, data_glob, max_positions=max_positions)
    all_white, all_black, all_counts, feature_offsets = _precompute_features(pieces)

    # Shuffle all arrays in unison
    n = len(scores)
    order = np.random.permutation(n)
    side_to_moves = side_to_moves[order]
    scores = scores[order]
    outcomes = outcomes[order]
    shuffled_counts = all_counts[order]
    new_offsets = np.zeros(n + 1, dtype=np.int64)
    np.cumsum(shuffled_counts, out=new_offsets[1:])
    old_starts = feature_offsets[order]
    flat_index = np.repeat(old_starts - new_offsets[:-1], shuffled_counts) + np.arange(len(all_white))
    all_white = all_white[flat_index]
    all_black = all_black[flat_index]

    return PositionDataset(side_to_moves, scores, outcomes, all_white, all_black, new_offsets)


# --- Training ---


def _fit_eval_scaling_factor(scores, outcomes):
    """Find the sigmoid scaling constant that best maps centipawn scores to win probabilities."""

    def error(k):
        predictions = expit(k * scores)
        errors = (predictions - outcomes) ** 2
        return np.mean(errors)

    scores = scores.cpu().numpy().astype(np.float64)
    outcomes = outcomes.cpu().numpy().astype(np.float64)
    return minimize_scalar(error, bounds=(0.0001, 0.1), method='bounded').x


def _compute_loss(prediction, outcome, score, side_to_move, eval_scaling_factor):
    """Weighted blend of outcome BCE and eval BCE.

    Score and outcome are stored from white's perspective, but the model outputs
    from the side-to-move's perspective. Flip targets for black-to-move positions."""
    stm_score = torch.where(side_to_move == WHITE, score, -score)
    stm_outcome = torch.where(side_to_move == WHITE, outcome, 1.0 - outcome)
    win_probability = torch.sigmoid(eval_scaling_factor * stm_score)
    eval_term = EVALUATION_WEIGHT * LOSS_FUNCTION(prediction, win_probability)
    outcome_term = (1 - EVALUATION_WEIGHT) * LOSS_FUNCTION(prediction, stm_outcome)
    return eval_term + outcome_term


def _train(num_epochs=NUM_EPOCHS, max_positions=MAX_POSITIONS, weights=None):
    """Run a training loop."""
    # Load training and validation data
    print('Loading training data...')
    training_dataset = _load_positions(TRAINING_DATA_DIR, TRAINING_DATA_GLOB, max_positions=max_positions)
    print('\nLoading validation data...')
    validation_dataset = _load_positions(VALIDATION_DATA_DIR, VALIDATION_DATA_GLOB)

    training_sampler = BatchSampler(len(training_dataset), TRAINNG_BATCH_SIZE)
    validation_sampler = BatchSampler(len(validation_dataset), TRAINNG_BATCH_SIZE)

    training_loader = DataLoader(training_dataset, batch_sampler=training_sampler, collate_fn=training_dataset.collate)
    validation_loader = DataLoader(validation_dataset, batch_sampler=validation_sampler, collate_fn=validation_dataset.collate)

    print()

    # Initialize model
    model = NNUE().to(DEVICE)
    weights_path = resolve(WEIGHTS_DIR, 'weights', '.pt', n=weights)
    if weights_path:
        checkpoint = torch.load(weights_path, weights_only=False)
        model.load_state_dict(checkpoint['model'])
        print(f'Loaded weights from {weights_path}')

    optimizer = torch.optim.AdamW(model.parameters(), lr=INITIAL_LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.StepLR(
        optimizer,
        step_size=LEARNING_RATE_STEP_SIZE,
        gamma=LEARNING_RATE_GAMMA
    )

    eval_scaling_factor = _fit_eval_scaling_factor(training_dataset.scores, training_dataset.outcomes)
    print(f'Evaluation scaling factor: {eval_scaling_factor:.6f}')
    print(f'Training on {len(training_dataset):,} positions, validating on {len(validation_dataset):,}')
    print(f'Device: {DEVICE}')

    save_path = next_path(WEIGHTS_DIR, 'weights', '.pt')
    print(f'Saving best weights to {save_path}')

    print(f'\n--- Training ---\n')
    lowest_validation_loss = float('inf')
    epochs_without_improvement = 0
    for epoch in range(num_epochs):
        t_epoch = time.perf_counter()

        # Training
        model.train()
        epoch_training_loss = 0
        for batch in training_loader:
            prediction = model(batch.white_indices, batch.white_offsets, batch.black_indices, batch.black_offsets, batch.side_to_move)
            loss = _compute_loss(prediction, batch.outcome, batch.score, batch.side_to_move, eval_scaling_factor)
            epoch_training_loss += loss.item()

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=GRADIENT_CLIP_MAX_NORM)
            optimizer.step()
        average_training_loss = epoch_training_loss / len(training_loader)

        # Validation
        model.eval()
        epoch_validation_loss = 0
        with torch.no_grad():
            for batch in validation_loader:
                prediction = model(batch.white_indices, batch.white_offsets, batch.black_indices, batch.black_offsets, batch.side_to_move)
                loss = _compute_loss(prediction, batch.outcome, batch.score, batch.side_to_move, eval_scaling_factor)
                epoch_validation_loss += loss.item()
        average_validation_loss = epoch_validation_loss / len(validation_loader)

        lr = scheduler.get_last_lr()[0]
        t_epoch = time.perf_counter() - t_epoch

        # Save weights if we get a new best (lowest) validation loss
        if average_validation_loss < lowest_validation_loss:
            lowest_validation_loss = average_validation_loss
            epochs_without_improvement = 0
            torch.save({
                'model': model.state_dict(),
                'eval_scaling_factor': eval_scaling_factor,
            }, save_path)
        else:
            epochs_without_improvement += 1

        print(f'| Epoch: {(epoch + 1):<3} | Training Loss: {average_training_loss:.6f} | Validation Loss: {average_validation_loss:.6f} | Learning Rate: {lr:.6f} | {t_epoch:.1f}s |')

        scheduler.step()

        if epochs_without_improvement >= EARLY_STOPPING_PATIENCE:
            print(f'\nEarly stopping: no improvement in {EARLY_STOPPING_PATIENCE} epochs')
            break

    print(f'\nBest validation loss: {lowest_validation_loss:.6f}')


def main():
    """Entry point for the training script."""
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', default=None, help='Weight file number to load (default: latest, "none" for fresh)')
    args = parser.parse_args()
    try:
        _train(weights=args.weights)
    except KeyboardInterrupt:
        print('\nStopping...')

if __name__ == '__main__':
    main()
