// Auto-generated by scripts/generators/search_params.py — do not edit manually

#pragma once

constexpr int DEFAULT_ASPIRATION_WINDOW = 67;
constexpr int DEFAULT_SCORE_DROP_THRESHOLD = 180;
constexpr int DEFAULT_NULL_MOVE_BASE_REDUCTION = 4;
constexpr int DEFAULT_NULL_MOVE_DEEPER_THRESHOLD = 8;
constexpr int DEFAULT_NULL_MOVE_MIN_DEPTH = 2;
constexpr int DEFAULT_FUTILITY_MARGIN_PER_DEPTH = 10;
constexpr int DEFAULT_FUTILITY_MARGIN_BASE = 77;
constexpr int DEFAULT_FUTILITY_MAX_DEPTH = 4;
constexpr int DEFAULT_SEE_CUTOFF = -113;
constexpr double DEFAULT_LMR_TUNING_CONSTANT = 1.317;
constexpr int DEFAULT_MINIMUM_IID_DEPTH = 6;
constexpr int DEFAULT_IID_DEPTH_DIVISOR = 2;
constexpr int DEFAULT_LMR_PV_REDUCTION = 1;
constexpr int DEFAULT_BEST_MOVE_MIN_STABILITY = 0;
constexpr int DEFAULT_NULL_MOVE_DEEP_REDUCTION = 5;
constexpr int DEFAULT_HISTORY_MALUS_DIVISOR = 2;
