// Auto-generated by scripts/generators/tm_params.py — do not edit manually

#pragma once

constexpr int DEFAULT_MOVES_LEFT_BASE = 11;
constexpr int DEFAULT_MOVES_LEFT_PHASE_SCALE = 78;
constexpr int DEFAULT_MIN_MOVES_NO_INCREMENT = 35;
constexpr double DEFAULT_INCREMENT_FRACTION = 0.918;
constexpr double DEFAULT_SOFT_FACTOR_NO_INCREMENT = 0.933;
constexpr double DEFAULT_SOFT_FACTOR_INCREMENT = 0.844;
constexpr double DEFAULT_HARD_FACTOR = 4.51;
constexpr int DEFAULT_HARD_CAP_DIVISOR = 2;
constexpr int DEFAULT_EMERGENCY_TRIGGER = 8;
constexpr int DEFAULT_EMERGENCY_SOFT_DIVISOR = 11;
constexpr int DEFAULT_EMERGENCY_HARD_DIVISOR = 22;
